/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfas;

import Diagnosticado.DiagnosticoOracion;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JLabel;

/**
 *
 * @author drymnz
 */
public class Menu extends javax.swing.JFrame {

    DiagnosticoOracion motor;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelDecir = new javax.swing.JLabel();
        JButtonVerificar = new javax.swing.JButton();
        JTextFieldEntrada = new javax.swing.JTextField();
        JLabelNumeroEntero = new javax.swing.JLabel();
        JLabelNumeroDecimal = new javax.swing.JLabel();
        LedDecimal = new Led.Led();
        LedEntero = new Led.Led();
        JLabelIdentificador = new javax.swing.JLabel();
        LedIdentificador = new Led.Led();
        JLabelSimbolo = new javax.swing.JLabel();
        LedSimbolo = new Led.Led();
        JLabelError = new javax.swing.JLabel();
        LedError = new Led.Led();
        JLabelDiagnosticoEntero = new javax.swing.JLabel();
        JLabelDiagnosticoDecimal = new javax.swing.JLabel();
        JLabelDiagnosticoIdentificador = new javax.swing.JLabel();
        JLabelDiagnosticoSimbolo = new javax.swing.JLabel();
        JLabelDiagnosticoError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelDecir.setText("Ingresar texto:");

        JButtonVerificar.setText("Verificar");
        JButtonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVerificarActionPerformed(evt);
            }
        });

        JLabelNumeroEntero.setText("Numero Entero");

        JLabelNumeroDecimal.setText("Numero Decimal");

        javax.swing.GroupLayout LedDecimalLayout = new javax.swing.GroupLayout(LedDecimal);
        LedDecimal.setLayout(LedDecimalLayout);
        LedDecimalLayout.setHorizontalGroup(
            LedDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LedDecimalLayout.setVerticalGroup(
            LedDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LedEnteroLayout = new javax.swing.GroupLayout(LedEntero);
        LedEntero.setLayout(LedEnteroLayout);
        LedEnteroLayout.setHorizontalGroup(
            LedEnteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        LedEnteroLayout.setVerticalGroup(
            LedEnteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        JLabelIdentificador.setText("Identificador");

        javax.swing.GroupLayout LedIdentificadorLayout = new javax.swing.GroupLayout(LedIdentificador);
        LedIdentificador.setLayout(LedIdentificadorLayout);
        LedIdentificadorLayout.setHorizontalGroup(
            LedIdentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LedIdentificadorLayout.setVerticalGroup(
            LedIdentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JLabelSimbolo.setText("Simbolo");

        javax.swing.GroupLayout LedSimboloLayout = new javax.swing.GroupLayout(LedSimbolo);
        LedSimbolo.setLayout(LedSimboloLayout);
        LedSimboloLayout.setHorizontalGroup(
            LedSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        LedSimboloLayout.setVerticalGroup(
            LedSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JLabelError.setText("Error");

        javax.swing.GroupLayout LedErrorLayout = new javax.swing.GroupLayout(LedError);
        LedError.setLayout(LedErrorLayout);
        LedErrorLayout.setHorizontalGroup(
            LedErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        LedErrorLayout.setVerticalGroup(
            LedErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JLabelDiagnosticoEntero.setText("jLabel1");

        JLabelDiagnosticoDecimal.setText("jLabel1");

        JLabelDiagnosticoIdentificador.setText("jLabel1");

        JLabelDiagnosticoSimbolo.setText("jLabel1");

        JLabelDiagnosticoError.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLabelDecir)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTextFieldEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonVerificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JLabelError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelSimbolo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelIdentificador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelNumeroDecimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(JLabelNumeroEntero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LedDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LedEntero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LedIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LedSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LedError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelDiagnosticoEntero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelDiagnosticoDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelDiagnosticoIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JLabelDiagnosticoError, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(JLabelDiagnosticoSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelDecir)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonVerificar)
                    .addComponent(JTextFieldEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelNumeroEntero)
                            .addComponent(JLabelDiagnosticoEntero))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LedDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelNumeroDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabelDiagnosticoDecimal)))
                    .addComponent(LedEntero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LedIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLabelIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JLabelDiagnosticoIdentificador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LedSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLabelSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JLabelDiagnosticoSimbolo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LedError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JLabelDiagnosticoError))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVerificarActionPerformed
        // TODO add your handling code here:
        if (!JTextFieldEntrada.getText().trim().equals("")) {
            motor = new DiagnosticoOracion(JTextFieldEntrada.getText());
            cambiarColorLed(0, JLabelDiagnosticoIdentificador, LedIdentificador);
            cambiarColorLed(1, JLabelDiagnosticoEntero, LedEntero);
            cambiarColorLed(2, JLabelDiagnosticoDecimal, LedDecimal);
            cambiarColorLed(3, JLabelDiagnosticoSimbolo, LedSimbolo);
            cambiarColorLed(4, JLabelDiagnosticoError, LedError);
        }
    }//GEN-LAST:event_JButtonVerificarActionPerformed
    private void cambiarColorLed(int posicion, JLabel JLabelDiagnostico, Led.Led led) {
        if (motor.getDiagnosticoListado()[posicion] != null) {
            led.setColor(Color.green);
            JLabelDiagnostico.setText(motor.getDiagnosticoListado()[posicion]);
        } else {
            led.setColor(Color.RED);
            JLabelDiagnostico.setText(motor.getDiagnosticoListado()[posicion]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonVerificar;
    private javax.swing.JLabel JLabelDecir;
    private javax.swing.JLabel JLabelDiagnosticoDecimal;
    private javax.swing.JLabel JLabelDiagnosticoEntero;
    private javax.swing.JLabel JLabelDiagnosticoError;
    private javax.swing.JLabel JLabelDiagnosticoIdentificador;
    private javax.swing.JLabel JLabelDiagnosticoSimbolo;
    private javax.swing.JLabel JLabelError;
    private javax.swing.JLabel JLabelIdentificador;
    private javax.swing.JLabel JLabelNumeroDecimal;
    private javax.swing.JLabel JLabelNumeroEntero;
    private javax.swing.JLabel JLabelSimbolo;
    private javax.swing.JTextField JTextFieldEntrada;
    private Led.Led LedDecimal;
    private Led.Led LedEntero;
    private Led.Led LedError;
    private Led.Led LedIdentificador;
    private Led.Led LedSimbolo;
    // End of variables declaration//GEN-END:variables
}
